### ISSUE TITLE
arm64 release

### ISSUE THREAD

**Issue by draeron** [SynologyOpenSource/synology-csi#1]
First: congrats on releasing a first version.

Anyway plan in releasing a ARM64 version of the images?

Don't know what your using as CI but there many option to easily build multiple targets with Github actions and goreleaser.

**Comment by draeron** [comment]
I created a fork with a auto build / github actions if you are interested in seeing how to do it. I haven't been able to create signed releases but still, it's quite an easy setup to do.

https://github.com/draeron/synology-csi

**Comment by chihyuwu** [comment]
@draeron Thank you for your feedback. I'll update the ARM/ARM64 version images soon.
And we'll introduce these auto build tools in the future.

**Comment by draeron** [comment]
I have yet succeeded in running the csi on my raspberry pi cluster but I haven't really investigated why (the plugins container doesn't print any output).

If I find something more concrete I'll open up an issue with concrete details. One thing I've seen is that the manifest provided in this repo use quay.io images for k8s csi containers but they've been moved to google gcr.io (k8s.gcr.io/sig-storage). Sadly gcr doesn't provide browsing but they are listed in this page: 

https://kubernetes-csi.github.io/docs/node-driver-registrar.html

**Comment by travisghansen** [comment]
If you need something immediately I recently added support for synology in my project here which supports arm: https://github.com/democratic-csi/democratic-csi

Glad to see another project for synology as it helps to see code and have other options available.

**Comment by toasterlint** [comment]
> 
> 
> I have yet succeeded in running the csi on my raspberry pi cluster but I haven't really investigated why (the plugins container doesn't print any output).
> 
> If I find something more concrete I'll open up an issue with concrete details. One thing I've seen is that the manifest provided in this repo use quay.io images for k8s csi containers but they've been moved to google gcr.io (k8s.gcr.io/sig-storage). Sadly gcr doesn't provide browsing but they are listed in this page:
> 
> https://kubernetes-csi.github.io/docs/node-driver-registrar.html

I was looking through your code, and while goreleaser is fairly new to me, based on the documentation I'm seeing and what you have in the Dockerfile.goreleaser file I'm not sure where the `synology-csi` file you are attempting to copy into the container is coming from:
https://github.com/draeron/synology-csi/blob/87980fbe729b60d0a6507976e5b9265c26befa29/Dockerfile.goreleaser#L17

I don't see anywhere in the automated build process that the regular Dockerfile is being called or just the a make on the repo to compile the synology-driver-csi binary.  So you may not be seeing any output as it may not actually be running anything.

**Comment by draeron** [comment]
goreleaser break Dockerfile encapsulation by building binaries outside docker, in the case of my fork, the compilation occurs during a github action. Compilation is done simply by calling `go build`. Having a makefile somewhat an anti pattern to goreleaser since it's supposed to be tool independant from the OS (ex: it doesn't make to be installed).

For each possibilities defined in the `builds` section of `.goreleaser.yml` a local directory will be created with the output. There is probably a better way to use Docker itself to compile each build but I went for the described method by goreleaser's author defined here (https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/).

**Comment by toasterlint** [comment]
@draeron Awesome, thanks for the explanation!  If the build system isn't running alpine (based on what I'm seeing in your workflow it's using ubuntu) that could be a potential issue since the end-result docker container still is.  Alpine is using `musl` vs most other distros using `glibc`.  If `actions/setup-go@v2` really is just running `go build` without specifying to statically link and/or setting `CGO_ENABLED=0` that could be an issue.

**Comment by draeron** [comment]
Indeed but cgo is disabled in the env section so it wouldn't compile if there was a reference to libc.

**Comment by toasterlint** [comment]
@draeron doh, disregard, I'm seeing that in the .goreleaser.yml file now...like I said, it's new to me!  However, the Ubuntu build image vs the Alpine run image may still be a factor.

**Comment by toasterlint** [comment]
I did have working versions of the plugin's container yesterday without using goreleaser and just updating the Makefile, but was having issues with the latest CSI-(Attacher|Resizer|etc) images from gcr not working, so abandoned it.  I'm running a mixed amd64 and arm64 cluster thus my interest :)

**Comment by toasterlint** [comment]
I see there is now an arm specific image out on Docker Hub...too bad it isn't a multi-arch image as specifying different image tags is problematic in a multi-arch cluster.

**Comment by draeron** [comment]
I modified my projet to use the project original makefile / Dockerfile. It works on my raspberry pi cluster.

![image](https://user-images.githubusercontent.com/2256246/133276820-c3cff1c6-7147-42d7-afdc-06ba75352354.png)

**Comment by toasterlint** [comment]
I noticed you didn’t specify any of the ldflags as a part of the goreleaser, that might be it.

I also figured out my issue as well.  My primary system is Windows based and when docker build was importing the chroot.sh file it was copying it into the container with the Windows line endings…another reason to switch back to Linux, lol.

**Comment by chihyuwu** [comment]
> I see there is now an arm specific image out on Docker Hub...too bad it isn't a multi-arch image as specifying different image tags is problematic in a multi-arch cluster.

I've updated a multi-arch image with the same tag on Docker Hub (and removed the one with the suffix -arm). Hope it can work in your multi-arch cluster.

**Comment by kingdonb** [comment]
I noticed it looks like the Makefile does not include any settings for building a multi-arch image and wanted to make sure it was documented for future contributors.

To get a multi-arch image, I needed to run:

```
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
```
to prepare my local docker host with the required emulators for the target architectures,

```
docker buildx create --use
```
to ensure the default docker driver for building isn't used (as it doesn't support multiarch)

Added a new target in my `Makefile`:

```
docker-build-multiarch:
        docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag $(IMAGE_TAG) . --push
```

Then run (with `REGISTRY_NAME` to ensure I can publish):

```
make docker-build-multiarch REGISTRY_NAME=kingdonb
```

Some credit to weaveworks/Watch#9 which needed a reviewer and showed me how to do this today :)

I can contribute this back in a PR if that would be helpful!
