### ISSUE TITLE
User permission for csi

### ISSUE THREAD

**Issue by kalle83** [SynologyOpenSource/synology-csi#13]
Hi all,

is there a way to use the synology-csi without an admin account/permission, with reduced permission?
It does not feel good that an admin account/service user with username/password is available in the kubernetes cluster and and potentially usable by others.

**Comment by chihyuwu** [comment]
Hi @kalle83,
We understand your concern. However, DSM allows only user accounts within the administrators group to have access to the SAN Manager package and to use related APIs. So, you can only use synology-csi with accounts with the admin privileges.

**Comment by kalle83** [comment]
@chihyuwu thank you for your response. That is a pity but at least it is possible to reduce the permission for an admin account and prohibit the login to DSM and other services.
