### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by cafsenra** [SynologyOpenSource/synology-csi#16]
I have installed csi synology driver but I am getting this error: "standard_init_linux.go:228: exec user process caused: exec format error"
All pods in csi-synology namespace are crashing :( with that message. Can anyone assist me? I am running a cluster k3s kubernetes on 6 raspberry pi v4 with ubuntu installed.

**Comment by johanvandeweerd** [comment]
The error message you get indicates that the container image you are running has a different architecture than what your hardware is running (x86 vs arm).
In you case the container images are only for x86 and your raspberry pi's have an ARM64 architecture (I had the same problem).

I forked this repository and changed the image to also support ARM, installed it and it worked like a charm.

You can give it a try yourself by cloning this repo and use that one instead: https://github.com/johanvandeweerd/synology-csi

**Comment by cafsenra** [comment]
Great news! I see that you used longhorn images! I am surprised that it works 😊! I will give a try on the weekend! Thank you for sharing your experience 😉! Best regards!

**Comment by cafsenra** [comment]
I have checked the solution provided by @johanvandeweerd and it works. Great job! I will close this issue as it is solved for now. Also I have made a fork and use the same logic from @johanvandeweerd to enable snapshots. Please feel free to check that on my repo: https://github.com/cafsenra/synology-csi/tree/arm64/release-v1.0.0 (branch arm64/release-v1.0.0). Once again credits to @johanvandeweerd!!
