### ISSUE TITLE
Upgrading to 1.1.0 breaks existing storageclasses with `RPC error: rpc error: code = InvalidArgument desc = Unknown protocol`

### ISSUE THREAD

**Issue by vaskozl** [SynologyOpenSource/synology-csi#34]
Since upgrading to 1.1.0 mounting no longer works. The daemonset csi-plugin logs:

```
2022-04-28T08:34:31Z [ERROR] [driver/utils.go:108] GRPC error: rpc error: code = InvalidArgument desc = Unknown protocol
```

I tried adding `protocol: iscsi` to my storage classes but kubernetes forbids me on the ground that parameters can't be edited after storage class creation.

I expect the csi-plugin to default to ISCSI and to be backwards compatible.

**Comment by chihyuwu** [comment]
Hi @vaskozl 
Thank you for letting us know! We'll fix it soon.
