### ISSUE TITLE
Couldn't find any host available to create volume

### ISSUE THREAD

**Issue by jrowinski3d** [SynologyOpenSource/synology-csi#42]
Using general defaults for the values and updating my connection strings in the config, l I am receiving this error:

```bash
Failed to create Volume: rpc error: code = Internal desc = Failed to get available location, err: DSM Api error. Error code:105
GRPC error: rpc error: code = Internal desc = Couldn't find any host available to create Volume
Any idea whats happening here? I saw a previous issue where updating the parameters to the StorageClass was the solution but it doesn't seem to have the same resolution for me.
```

Thanks for any help!

**Comment by jrowinski3d** [comment]
Problem was with the `path` I had defined in the StorageClass, as well as the user didn't have the appropriate rights for the connection. My **admin** can connect but my other user cannot. Still looking into which permission determines that

**Comment by gjrtimmer** [comment]
@jrowinski3d Had the same problem, solution is to give the user which connects to the Synology the following:
* Member of "Administrators"
* Applications
  * DSM
  * SMB

Dey the rest of the applications and adding to the administrator group will probably make it work.

**Comment by appkins** [comment]
> [@jrowinski3d](https://github.com/jrowinski3d) Had the same problem, solution is to give the user which connects to the Synology the following:
> 
> * Member of "Administrators"
> * Applications
>   
>   * DSM
>   * SMB
> 
> Dey the rest of the applications and adding to the administrator group will probably make it work.

This was a godsend. For whatever reason, the application user _must_ be in the `administrators` group. This seems like a serious security no-no, but it answers many of the open issues in this repo.
