### ISSUE TITLE
k8s version check: --short not longer supported

### ISSUE THREAD

**Issue by ppuschmann** [SynologyOpenSource/synology-csi#61]
Apparently newer versions of `kubectl` do not longer support the argument `--short` for the version check.

Output:
```
$ ./scripts/deploy.sh install --basic
==== Creates namespace and secrets, then installs synology-csi ====
error: unknown flag: --short
See 'kubectl version --help' for usage.
Version not supported:
```

Possible fix:
Remove the argument `--short` from https://github.com/SynologyOpenSource/synology-csi/blob/main/scripts/deploy.sh#L13

Example output from kubectl:

```
$ kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4+k3s1
```

This should be fine.

**Comment by chihyuwu** [comment]
Fixed in commit 6c990fc9541572c23e31312b63b5bec452ca49e0. Closing this issue.
