### ISSUE TITLE
Cannot control ownership and permissions for mounted volumes

### ISSUE THREAD

**Issue by christian-schlichtherle** [SynologyOpenSource/synology-csi#7]
First of all, thank you so much for this driver - it's a great start!

After updating images and cluster roles, I have the CSI working to the point that volumes are automatically created, attached and mounted in containers. But for some reason, the ownership and permissions are not exactly the same as they are when I was manually creating a PersistentVolume (though I did not specify anything to control it). As a result, all the containers I tried bail out with a permission error saying that they cannot write files in the mounted volumes.

I have ssh'ed to the nodes and verified that the ownership and permission of the mounted directories is now root:root and 755, respectively. For some reason, my containers are not running as root, so they don't have permission.

I wonder how to control ownership and permissions for the mount paths?

**Comment by wamdy** [comment]
可以提供一个链接吗？@christian-schlichtherle
