### ISSUE TITLE
As of v1.28.4, kubectl version Flag --short has been removed

### ISSUE THREAD

**Issue by vitofly** [SynologyOpenSource/synology-csi#74]
Hi Team, I noticed the Flag --short for 'kubectl version' is not supported on v1.28.4. The --short output becomes the default. 

Output from 'kubectl version':
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4

Line 13 in ./scripts/deploy.sh needs to be updated to parse versions correctly from 'kubectl version' for v1.28.4+ (I remember it was working on 1.28.3 but please double check).

Low Priority as workaround is to delete the flag '--short' in the deploy.sh script.

**Comment by chihyuwu** [comment]
Fixed in commit 6c990fc9541572c23e31312b63b5bec452ca49e0. Closing this issue.
